x1,b1=map(int,input("Enter 1st line").split(' '))
x2,b2=map(int,input("Enter 2nd line").split(' '))
x3,b3=map(int,input("Enter 3rd line").split(' '))
if (x1==b2 and x2==x3) or(b1==b2 and b2==b3) or (abs(x1-x2)==abs(x2-x3) and abs(b1-b2)==abs(b2-b3)):print("yes")
else:print("no")
